FROM golang:1.16.6-alpine as prvd-cli

RUN apk --no-cache --virtual build-dependencies add git make docker g++ \
    && apk add make \
    && apk add curl \
    && apk add bash \
    && apk add docker

RUN git clone https://github.com/provideplatform/provide-cli \
    && cd provide-cli && make install

FROM node:10.15.3-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app


RUN apk update && apk upgrade\
    && apk add curl --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main \
    && docker-compose
RUN apk add docker docker-compose --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community 
RUN apk add make 

COPY --from=prvd-cli /usr/local/go/ /usr/local/go/
COPY --from=prvd-cli /go/bin/prvd /usr/local/go/bin/prvd
ENV PATH="/usr/local/go/bin:${PATH}"


COPY package.json /usr/src/app/

RUN npm install

COPY . /usr/src/app


CMD ["tail", "-f", "/dev/null"]