# GOLANG IMAGE
FROM golang:1.16.5-alpine

WORKDIR /go/src/github.com/provideplatform/provide-cli/
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build .

# NODE IMAGE
FROM node:10.15.3-alpine

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json /usr/src/app/

RUN apk --no-cache --virtual build-dependencies add git python make docker g++ \
    && apk add curl \
    && git config --global url."https://".insteadOf git:// \
    && npm install  \
    && apk add make \
    && apk add docker \
    && apk del build-dependencies

RUN && apk add git bash && git clone https://github.com/vishnubob/wait-for-it.git
    
RUN git clone https://github.com/provideplatform/provide-cli \
    && cd provide-cli && make install
COPY . /usr/src/app

COPY entrypoint.sh /usr/src/app
RUN chmod +x /usr/src/app/entrypoint.sh

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
CMD ["npm","run","test"]