#!/usr/bin/env bash

export ZOKRATES_PROVING_SCHEME=G16

build() {
    (cd .. && cargo +nightly -Z package-features build --release --package zokrates_cli)
}

unbuild() {
    (cd .. && cargo clean)
}

clean() {
    rm -rf out* witness *.json *.key *.raw *.sol
}

compile() {
    export ZOKRATES_HOME=../zokrates_stdlib/stdlib/
    ../target/release/zokrates compile -i test.zok
}

setup() {
    ../target/release/zokrates setup
}

witness() {
    [ -z $1 ] && echo "missing args" >&2 && return 1
    ../target/release/zokrates compute-witness -a "$@"
}

generate() {
    ../target/release/zokrates generate-proof
}

err() {
    echo "Possible commands: build, unbuild, clean, compile, setup, witness, generate"
}

main() {
    local cmd; cmd=$1; shift
    [ -z "$cmd" ] && err && return 1
    [ $cmd != build ] \
        && [ $cmd != unbuild ] \
        && [ $cmd != clean ] \
        && [ $cmd != compile ] \
        && [ $cmd != setup ] \
        && [ $cmd != witness ] \
        && [ $cmd != generate ] \
        && err && return 1
    $cmd "$@"
}

main "$@"
