import merge from 'lodash/merge';

/**
 * Updates an entity cache in response to any action with response.entities.
 * This property is generated by `normalizr`.
 *
 * @param {object} state - Current partial state for this reducer.
 * @param {object} action - Redux action object.
 * @return {object} - New state object.
 */
function entitiesReducer(state = {}, action) {
  const { payload } = action;

  if (payload && payload.entities) {
    return merge({}, state, action.payload.entities);
  }

  return state;
}

export default entitiesReducer;
